version: "3.8"
services:
  postgres:
    image: postgres:18-alpine
    restart: always
    environment:
      - POSTGRES_DB=somedb
      - POSTGRES_USER=someuser
      - POSTGRES_PASSWORD=5up3r53cretP@5sw0rd
    ports:
      - "5432:5432"
